//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.15 at 06:35:01 PM MEZ 
//


package at.sti2.rif4j.test.suite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import at.sti2.rif4j.test.suite.Combinations;
import at.sti2.rif4j.test.suite.DescriptionType;
import at.sti2.rif4j.test.suite.DialectType;
import at.sti2.rif4j.test.suite.DocumentType;
import at.sti2.rif4j.test.suite.StatusType;


/**
 * <p>Java class for syntaxTest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="syntaxTest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2009/10/rif-test#}commonTestCaseInfo"/>
 *         &lt;element name="InputDocument" type="{http://www.w3.org/2009/10/rif-test#}documentType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="src" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "syntaxTest", propOrder = {
    "status",
    "dialect",
    "combinations",
    "purpose",
    "description",
    "importedDocument",
    "inputDocument"
})
public class SyntaxTest {

    @XmlElement(required = true)
    protected StatusType status;
    @XmlElement(required = true)
    protected List<DialectType> dialect;
    @XmlElement(name = "Combinations")
    protected Combinations combinations;
    @XmlElement(required = true)
    protected DescriptionType purpose;
    protected DescriptionType description;
    @XmlElement(name = "ImportedDocument")
    protected List<DocumentType> importedDocument;
    @XmlElement(name = "InputDocument", required = true)
    protected DocumentType inputDocument;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String src;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setStatus(StatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the dialect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dialect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDialect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DialectType }
     * 
     * 
     */
    public List<DialectType> getDialect() {
        if (dialect == null) {
            dialect = new ArrayList<DialectType>();
        }
        return this.dialect;
    }

    /**
     * Gets the value of the combinations property.
     * 
     * @return
     *     possible object is
     *     {@link Combinations }
     *     
     */
    public Combinations getCombinations() {
        return combinations;
    }

    /**
     * Sets the value of the combinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Combinations }
     *     
     */
    public void setCombinations(Combinations value) {
        this.combinations = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setPurpose(DescriptionType value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setDescription(DescriptionType value) {
        this.description = value;
    }

    /**
     * Gets the value of the importedDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the importedDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImportedDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentType }
     * 
     * 
     */
    public List<DocumentType> getImportedDocument() {
        if (importedDocument == null) {
            importedDocument = new ArrayList<DocumentType>();
        }
        return this.importedDocument;
    }

    /**
     * Gets the value of the inputDocument property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentType }
     *     
     */
    public DocumentType getInputDocument() {
        return inputDocument;
    }

    /**
     * Sets the value of the inputDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentType }
     *     
     */
    public void setInputDocument(DocumentType value) {
        this.inputDocument = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

}
