//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.15 at 06:35:01 PM MEZ 
//


package at.sti2.rif4j.test.suite;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import at.sti2.rif4j.test.suite.NegativeEntailmentTest;
import at.sti2.rif4j.test.suite.PositiveEntailmentTest;
import at.sti2.rif4j.test.suite.SyntaxTest;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.w3.org/2009/10/rif-test#}TestCase" maxOccurs="unbounded"/>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testCase"
})
@XmlRootElement(name = "TestSuite")
public class TestSuite {

    @XmlElementRefs({
        @XmlElementRef(name = "ImportRejectionTest", namespace = "http://www.w3.org/2009/10/rif-test#", type = JAXBElement.class),
        @XmlElementRef(name = "PositiveSyntaxTest", namespace = "http://www.w3.org/2009/10/rif-test#", type = JAXBElement.class),
        @XmlElementRef(name = "NegativeSyntaxTest", namespace = "http://www.w3.org/2009/10/rif-test#", type = JAXBElement.class),
        @XmlElementRef(name = "PositiveEntailmentTest", namespace = "http://www.w3.org/2009/10/rif-test#", type = PositiveEntailmentTest.class),
        @XmlElementRef(name = "NegativeEntailmentTest", namespace = "http://www.w3.org/2009/10/rif-test#", type = NegativeEntailmentTest.class)
    })
    protected List<Object> testCase;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the testCase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testCase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestCase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PositiveEntailmentTest }
     * {@link JAXBElement }{@code <}{@link SyntaxTest }{@code >}
     * {@link JAXBElement }{@code <}{@link SyntaxTest }{@code >}
     * {@link NegativeEntailmentTest }
     * {@link JAXBElement }{@code <}{@link SyntaxTest }{@code >}
     * 
     * 
     */
    public List<Object> getTestCase() {
        if (testCase == null) {
            testCase = new ArrayList<Object>();
        }
        return this.testCase;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

}
