//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.15 at 06:35:01 PM MEZ 
//


package at.sti2.rif4j.test.suite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for documentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="documentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Normative">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="remote" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="syntax" type="{http://www.w3.org/2009/10/rif-test#}nSyntaxType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Presentation" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="syntax" use="required" type="{http://www.w3.org/2009/10/rif-test#}pSyntaxType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentType", propOrder = {
    "normative",
    "presentation"
})
public class DocumentType {

    @XmlElement(name = "Normative", required = true)
    protected DocumentType.Normative normative;
    @XmlElement(name = "Presentation")
    protected List<DocumentType.Presentation> presentation;

    /**
     * Gets the value of the normative property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentType.Normative }
     *     
     */
    public DocumentType.Normative getNormative() {
        return normative;
    }

    /**
     * Sets the value of the normative property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentType.Normative }
     *     
     */
    public void setNormative(DocumentType.Normative value) {
        this.normative = value;
    }

    /**
     * Gets the value of the presentation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presentation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresentation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentType.Presentation }
     * 
     * 
     */
    public List<DocumentType.Presentation> getPresentation() {
        if (presentation == null) {
            presentation = new ArrayList<DocumentType.Presentation>();
        }
        return this.presentation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="remote" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="syntax" type="{http://www.w3.org/2009/10/rif-test#}nSyntaxType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "remote"
    })
    public static class Normative {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected List<String> remote;
        @XmlAttribute
        protected NSyntaxType syntax;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the remote property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the remote property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRemote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRemote() {
            if (remote == null) {
                remote = new ArrayList<String>();
            }
            return this.remote;
        }

        /**
         * Gets the value of the syntax property.
         * 
         * @return
         *     possible object is
         *     {@link NSyntaxType }
         *     
         */
        public NSyntaxType getSyntax() {
            return syntax;
        }

        /**
         * Sets the value of the syntax property.
         * 
         * @param value
         *     allowed object is
         *     {@link NSyntaxType }
         *     
         */
        public void setSyntax(NSyntaxType value) {
            this.syntax = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="syntax" use="required" type="{http://www.w3.org/2009/10/rif-test#}pSyntaxType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Presentation {

        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected PSyntaxType syntax;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the syntax property.
         * 
         * @return
         *     possible object is
         *     {@link PSyntaxType }
         *     
         */
        public PSyntaxType getSyntax() {
            return syntax;
        }

        /**
         * Sets the value of the syntax property.
         * 
         * @param value
         *     allowed object is
         *     {@link PSyntaxType }
         *     
         */
        public void setSyntax(PSyntaxType value) {
            this.syntax = value;
        }

    }

}
