//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.15 at 06:35:01 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2009/10/rif-test#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package at.sti2.rif4j.test.suite;
