//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.15 at 06:35:01 PM MEZ 
//


package at.sti2.rif4j.test.suite;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pSyntaxType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="pSyntaxType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RIFBLD-PS"/>
 *     &lt;enumeration value="RIFPRD-PS"/>
 *     &lt;enumeration value="NTriples"/>
 *     &lt;enumeration value="Turtle"/>
 *     &lt;enumeration value="OWL2 Functional Syntax"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "pSyntaxType")
@XmlEnum
public enum PSyntaxType {

    @XmlEnumValue("RIFBLD-PS")
    RIFBLD_PS("RIFBLD-PS"),
    @XmlEnumValue("RIFPRD-PS")
    RIFPRD_PS("RIFPRD-PS"),
    @XmlEnumValue("NTriples")
    N_TRIPLES("NTriples"),
    @XmlEnumValue("Turtle")
    TURTLE("Turtle"),
    @XmlEnumValue("OWL2 Functional Syntax")
    OWL_2_FUNCTIONAL_SYNTAX("OWL2 Functional Syntax");
    private final String value;

    PSyntaxType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PSyntaxType fromValue(String v) {
        for (PSyntaxType c: PSyntaxType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
